* Sprouts game board

Sprouts is yet another game invented by John Conway!  There is an
article about it in [[http://nrich.maths.org/2413][Sprouts Explained]].

This project is merely an exercise for me to explore [[http://paperjs.org/][Paper.js]] and
JavaScript.  The tool is still fairly modest, it could be improved in
many ways, see issues below.

** Playing

To play, get the mouse near a sprout, but not on the sprout itself,
then draw a connection line by clicking and dragging near another (or
the same) sprout.  When you release the mouse, your line is split in
two and a new sprout gets added in the middle.  If a region becomes
too crowded, you may drag sprouts around by clicking directly on the
sprouts themselves, yet pay attention while doing so at not having
lines crossing each other.  To re-initialize the game, reload the
page.

** Installation

To install, you also need a prepared copy of [[http://paperjs.org/][Paper.js]].  I keep mine in
the =js/= subdirectory of the Web site: adjust to taste!

** General issues

- Should add buttons for selecting the number of initial sprouts,
  deciding of options like animation, debugging, etc.

- Should add an Undo button, and maybe button to remove any sprout.

- A single line should not be allowed to cross itself.

- A line should not touch a sprout, except the limiting ones.

- An isolated, unreachable sprout should be marked dead.

- The end of the game should be detected and reported.

** Animation issues

- Animation is explored on the =animation= branch on GitHub and stays
  away from the =master= branch, until it becomes a bit satisfactory!

- Aim that the whole display occupies maybe .75 of the view area.  If
  too big, slightly decrease =K=, if too small, slightly increase =K= (=K=
  is explained below).

- Lines should repel each other, and should repel neighbouring sprouts
  as well.

- Have sprouts interact on one another using =(1 / K*d - 1 / d^2)=, a
  positive value attracts, a negative value repels.  In this way, two
  sprouts in equilibrium have a distance =K= between them.  For now, I
  rather tried the simpler =(K - d)= and found out that sprouts displace
  far too much: any usable dynamic ought to correctly handle line
  repulsion from the start.

- Unattended lines should progressively smooth and simplify, given
  they stay separate of course.

- Have the speed of the animation depends on the travelled distance,
  rather than one pixel at most per frame display, bigger the distance
  and bigger the speed.

François
