* Sprouts game board

Sprouts is yet another game invented by John Conway!  There is an
article about it in [[http://nrich.maths.org/2413][Sprouts Explained]].

** Installation

To install, you also need a prepared copy of [[http://paperjs.org/][Paper.js]].  I keep mine in
the =js/= subdirectory of the Web site: adjust to taste!

** Usage

To play, get the mouse near a sprout (not on the sprout itself, I
reserve this for something else), then click and drag near another (or
the same) sprout.  To re-initialize the game, reload the page.

** Justification

This is an tiny exercise for me to play with =paper.js= and JavaScript,
which I publish a bit prematurely for the sake of collaboration.  The
tool is still very modest, a lot of details are missing, big and
small.

François
** General issues

- Buttons for selecting the number of initial sprouts, reinitializing
  the game, deciding about different colorations for dead sprouts,
  deciding animation, etc.

- Undo button, and maybe button to remove any sprout.

- A single curve should not be allowed to cross itself.

- A curve should not touch a sprout, except the limiting ones.

- An isolated, unreachable sprout should be marked dead.

- The end of the game should be detected and reported.

** Animation issues

- Have the speed of the animation for a sprout depends on the
  travelled distance: bigger the distance and bigger the speed.

- Have sprouts attract each other using K / d, and repell each other
  using 1 / d^2.  In this way, two sprouts in equilibrium have a
  distance K between them.

- Aim the whole display to occupy maybe .75 of the view area.  If too
  big, slightly decrease K, if too small, slightly increase K.

- Given a curve between two moving sprouts, compute a matrix or
  something able to map the sprouts correctly, then use it to displace
  all segments in the curve.  The matrix mmigh also include the
  overall recentering displacement as well.  If a rotation is involved
  by the matrix, it is likely that the rotation should be applied to
  curve parameters as well.

- Curves should repell each other, and should repell neighbouring
  sprouts as well.

- Curves should progressively smooth and simplify, given they stay
  separate of course.

- Capability for dragging sprouts around, with all curves correctly
  following.
